---
- name: Install and Configure Apache Tomcat
  hosts: app_servers
  become: yes
  vars:
    # Versions
    tomcat_version: "9.0.85"
    java_version: "17"
    # Tomcat user/group
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_home: "/opt/tomcat"
    # 🔥 Dynamically get Jenkins IP from inventory
    jenkins_ip: "{{ hostvars[groups['jenkins'][0]].ansible_host }}"
    # 🔒 Credentials (use Ansible Vault in real environments)
    tomcat_admin_user: "admin"
    tomcat_admin_pass: "CHANGE_ME_ADMIN_PASSWORD"
    tomcat_deployer_user: "deployer"
    tomcat_deployer_pass: "CHANGE_ME_DEPLOYER_PASSWORD"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Create tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        home: "{{ tomcat_home }}"
        createhome: no
        shell: /bin/false

    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        mode: "0644"

    - name: Create Tomcat directory
      file:
        path: "{{ tomcat_home }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_home }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Set permissions on Tomcat directories
      file:
        path: "{{ tomcat_home }}/{{ item }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "0755"
        recurse: yes
      loop:
        - bin
        - conf
        - lib
        - logs
        - temp
        - webapps
        - work

    - name: Create Tomcat systemd service
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target
          
          [Service]
          Type=forking
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=CATALINA_PID={{ tomcat_home }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_home }}
          Environment=CATALINA_BASE={{ tomcat_home }}
          ExecStart={{ tomcat_home }}/bin/startup.sh
          ExecStop={{ tomcat_home }}/bin/shutdown.sh
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target

    # 🔧 FIX 1: Complete tomcat-users.xml
    - name: Configure Tomcat users
      copy:
        dest: "{{ tomcat_home }}/conf/tomcat-users.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <tomcat-users xmlns="http://tomcat.apache.org/xml"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                        version="1.0">
            <!-- Roles -->
            <role rolename="manager-gui"/>
            <role rolename="manager-script"/>
            <role rolename="manager-jmx"/>
            <role rolename="manager-status"/>
            
            <!-- Admin user -->
            <user username="{{ tomcat_admin_user }}" 
                  password="{{ tomcat_admin_pass }}" 
                  roles="manager-gui,manager-script,manager-jmx,manager-status"/>
            
            <!-- Deployer user for Jenkins -->
            <user username="{{ tomcat_deployer_user }}" 
                  password="{{ tomcat_deployer_pass }}" 
                  roles="manager-script"/>
          </tomcat-users>

    # 🔧 FIX 2: Allow Jenkins IP to access Manager app
    - name: Configure Manager app to allow Jenkins access
      copy:
        dest: "{{ tomcat_home }}/webapps/manager/META-INF/context.xml"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <Context antiResourceLocking="false" privileged="true">
            <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
                             sameSiteCookies="strict" />
            <!-- Allow localhost and Jenkins IP -->
            <Valve className="org.apache.catalina.valves.RemoteAddrValve"
                   allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|{{ jenkins_ip }}|10\.\d+\.\d+\.\d+" />
            <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
          </Context>

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: Wait for Tomcat to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Display Tomcat status
      debug:
        msg: 
          - "Tomcat installed at {{ tomcat_home }}"
          - "Access Manager at http://{{ ansible_host }}:8080/manager"
          - "Deployer user: {{ tomcat_deployer_user }}"
          - "Jenkins IP allowed: {{ jenkins_ip }}"